// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/v1/database.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModuleProto represents an installed Go module with all its metadata
type ModuleProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                       // Module path (e.g., github.com/user/repo)
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                 // Installed version (e.g., v1.2.3)
	Versions          []string               `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`                                               // All available versions
	Dependencies      []*DependencyProto     `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`                                       // Module dependencies
	Hash              string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`                                                       // SHA256 hash of module@version
	TimestampUnixNano int64                  `protobuf:"varint,6,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"` // Installation timestamp in Unix nanoseconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModuleProto) Reset() {
	*x = ModuleProto{}
	mi := &file_proto_v1_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleProto) ProtoMessage() {}

func (x *ModuleProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleProto.ProtoReflect.Descriptor instead.
func (*ModuleProto) Descriptor() ([]byte, []int) {
	return file_proto_v1_database_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleProto) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ModuleProto) GetDependencies() []*DependencyProto {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ModuleProto) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ModuleProto) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

// DependencyProto represents a single dependency with potential nested dependencies
type DependencyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                 // Dependency module path
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`           // Dependency version
	Versions      []string               `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`         // Available versions for this dependency
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`                 // SHA256 hash of dependency@version
	Dependencies  []*DependencyProto     `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"` // Nested dependencies (recursive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyProto) Reset() {
	*x = DependencyProto{}
	mi := &file_proto_v1_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyProto) ProtoMessage() {}

func (x *DependencyProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyProto.ProtoReflect.Descriptor instead.
func (*DependencyProto) Descriptor() ([]byte, []int) {
	return file_proto_v1_database_proto_rawDescGZIP(), []int{1}
}

func (x *DependencyProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DependencyProto) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *DependencyProto) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DependencyProto) GetDependencies() []*DependencyProto {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// DependenciesProto wraps a list of dependencies for a module
type DependenciesProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []*DependencyProto     `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependenciesProto) Reset() {
	*x = DependenciesProto{}
	mi := &file_proto_v1_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependenciesProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependenciesProto) ProtoMessage() {}

func (x *DependenciesProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependenciesProto.ProtoReflect.Descriptor instead.
func (*DependenciesProto) Descriptor() ([]byte, []int) {
	return file_proto_v1_database_proto_rawDescGZIP(), []int{2}
}

func (x *DependenciesProto) GetDependencies() []*DependencyProto {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// VersionListProto stores a list of versions for secondary indexing
type VersionListProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []string               `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionListProto) Reset() {
	*x = VersionListProto{}
	mi := &file_proto_v1_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionListProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionListProto) ProtoMessage() {}

func (x *VersionListProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionListProto.ProtoReflect.Descriptor instead.
func (*VersionListProto) Descriptor() ([]byte, []int) {
	return file_proto_v1_database_proto_rawDescGZIP(), []int{3}
}

func (x *VersionListProto) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_proto_v1_database_proto protoreflect.FileDescriptor

const file_proto_v1_database_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/database.proto\x12\bdatabase\"\xda\x01\n" +
	"\vModuleProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bversions\x18\x03 \x03(\tR\bversions\x12=\n" +
	"\fdependencies\x18\x04 \x03(\v2\x19.database.DependencyProtoR\fdependencies\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12.\n" +
	"\x13timestamp_unix_nano\x18\x06 \x01(\x03R\x11timestampUnixNano\"\xae\x01\n" +
	"\x0fDependencyProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bversions\x18\x03 \x03(\tR\bversions\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12=\n" +
	"\fdependencies\x18\x05 \x03(\v2\x19.database.DependencyProtoR\fdependencies\"R\n" +
	"\x11DependenciesProto\x12=\n" +
	"\fdependencies\x18\x01 \x03(\v2\x19.database.DependencyProtoR\fdependencies\".\n" +
	"\x10VersionListProto\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\tR\bversionsB$Z\"github.com/inovacc/glix/pkg/api/v1b\x06proto3"

var (
	file_proto_v1_database_proto_rawDescOnce sync.Once
	file_proto_v1_database_proto_rawDescData []byte
)

func file_proto_v1_database_proto_rawDescGZIP() []byte {
	file_proto_v1_database_proto_rawDescOnce.Do(func() {
		file_proto_v1_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_database_proto_rawDesc), len(file_proto_v1_database_proto_rawDesc)))
	})
	return file_proto_v1_database_proto_rawDescData
}

var file_proto_v1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_database_proto_goTypes = []any{
	(*ModuleProto)(nil),       // 0: database.ModuleProto
	(*DependencyProto)(nil),   // 1: database.DependencyProto
	(*DependenciesProto)(nil), // 2: database.DependenciesProto
	(*VersionListProto)(nil),  // 3: database.VersionListProto
}
var file_proto_v1_database_proto_depIdxs = []int32{
	1, // 0: database.ModuleProto.dependencies:type_name -> database.DependencyProto
	1, // 1: database.DependencyProto.dependencies:type_name -> database.DependencyProto
	1, // 2: database.DependenciesProto.dependencies:type_name -> database.DependencyProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_database_proto_init() }
func file_proto_v1_database_proto_init() {
	if File_proto_v1_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_database_proto_rawDesc), len(file_proto_v1_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_database_proto_goTypes,
		DependencyIndexes: file_proto_v1_database_proto_depIdxs,
		MessageInfos:      file_proto_v1_database_proto_msgTypes,
	}.Build()
	File_proto_v1_database_proto = out.File
	file_proto_v1_database_proto_goTypes = nil
	file_proto_v1_database_proto_depIdxs = nil
}
