// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputLine_Stream int32

const (
	OutputLine_STDOUT OutputLine_Stream = 0
	OutputLine_STDERR OutputLine_Stream = 1
)

// Enum value maps for OutputLine_Stream.
var (
	OutputLine_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	OutputLine_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x OutputLine_Stream) Enum() *OutputLine_Stream {
	p := new(OutputLine_Stream)
	*p = x
	return p
}

func (x OutputLine_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputLine_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_service_proto_enumTypes[0].Descriptor()
}

func (OutputLine_Stream) Type() protoreflect.EnumType {
	return &file_proto_v1_service_proto_enumTypes[0]
}

func (x OutputLine_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputLine_Stream.Descriptor instead.
func (OutputLine_Stream) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{15, 0}
}

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                           // Computer hostname or custom namespace
	DatabasePath  string                 `protobuf:"bytes,2,opt,name=database_path,json=databasePath,proto3" json:"database_path,omitempty"` // Path to BoltDB file
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                    // gRPC server port
	BindAddress   string                 `protobuf:"bytes,4,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`    // Address to bind (default: localhost)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proto_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServerConfig) GetDatabasePath() string {
	if x != nil {
		return x.DatabasePath
	}
	return ""
}

func (x *ServerConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerConfig) GetBindAddress() string {
	if x != nil {
		return x.BindAddress
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DatabasePath  string                 `protobuf:"bytes,3,opt,name=database_path,json=databasePath,proto3" json:"database_path,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ModuleCount   int64                  `protobuf:"varint,6,opt,name=module_count,json=moduleCount,proto3" json:"module_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_proto_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServerStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServerStatus) GetDatabasePath() string {
	if x != nil {
		return x.DatabasePath
	}
	return ""
}

func (x *ServerStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerStatus) GetModuleCount() int64 {
	if x != nil {
		return x.ModuleCount
	}
	return 0
}

// StoreModuleRequest is used by the CLI to store module info after local installation
type StoreModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleProto           `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Dependencies  *DependenciesProto     `protobuf:"bytes,2,opt,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreModuleRequest) Reset() {
	*x = StoreModuleRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreModuleRequest) ProtoMessage() {}

func (x *StoreModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreModuleRequest.ProtoReflect.Descriptor instead.
func (*StoreModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *StoreModuleRequest) GetModule() *ModuleProto {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *StoreModuleRequest) GetDependencies() *DependenciesProto {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type StoreModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreModuleResponse) Reset() {
	*x = StoreModuleResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreModuleResponse) ProtoMessage() {}

func (x *StoreModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreModuleResponse.ProtoReflect.Descriptor instead.
func (*StoreModuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *StoreModuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreModuleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModulePath    string                 `protobuf:"bytes,1,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`        // e.g., github.com/user/repo
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                // Optional: specific version or "latest"
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`                                   // Force reinstall even if exists
	StreamOutput  bool                   `protobuf:"varint,4,opt,name=stream_output,json=streamOutput,proto3" json:"stream_output,omitempty"` // Enable real-time output streaming
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *InstallRequest) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *InstallRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *InstallRequest) GetStreamOutput() bool {
	if x != nil {
		return x.StreamOutput
	}
	return false
}

type InstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleProto           `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *InstallResponse) GetModule() *ModuleProto {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *InstallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModulePath    string                 `protobuf:"bytes,1,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Optional: specific version or all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveRequest) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *RemoveRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListModulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                            // Pagination limit
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                          // Pagination offset
	NameFilter    string                 `protobuf:"bytes,3,opt,name=name_filter,json=nameFilter,proto3" json:"name_filter,omitempty"` // Optional name filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListModulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListModulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListModulesRequest) GetNameFilter() string {
	if x != nil {
		return x.NameFilter
	}
	return ""
}

type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ModuleProto         `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListModulesResponse) GetModules() []*ModuleProto {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ListModulesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Optional: if empty, returns latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleRequest) Reset() {
	*x = GetModuleRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleRequest) ProtoMessage() {}

func (x *GetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleRequest.ProtoReflect.Descriptor instead.
func (*GetModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleProto           `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleResponse) Reset() {
	*x = GetModuleResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleResponse) ProtoMessage() {}

func (x *GetModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleResponse.ProtoReflect.Descriptor instead.
func (*GetModuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetModuleResponse) GetModule() *ModuleProto {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetModuleResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  *DependenciesProto     `protobuf:"bytes,1,opt,name=dependencies,proto3" json:"dependencies,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependenciesResponse) Reset() {
	*x = GetDependenciesResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependenciesResponse) ProtoMessage() {}

func (x *GetDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependenciesResponse.ProtoReflect.Descriptor instead.
func (*GetDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetDependenciesResponse) GetDependencies() *DependenciesProto {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *GetDependenciesResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModulePath    string                 `protobuf:"bytes,1,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	StreamOutput  bool                   `protobuf:"varint,2,opt,name=stream_output,json=streamOutput,proto3" json:"stream_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRequest) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *UpdateRequest) GetStreamOutput() bool {
	if x != nil {
		return x.StreamOutput
	}
	return false
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldModule     *ModuleProto           `protobuf:"bytes,1,opt,name=old_module,json=oldModule,proto3" json:"old_module,omitempty"`
	NewModule     *ModuleProto           `protobuf:"bytes,2,opt,name=new_module,json=newModule,proto3" json:"new_module,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateResponse) GetOldModule() *ModuleProto {
	if x != nil {
		return x.OldModule
	}
	return nil
}

func (x *UpdateResponse) GetNewModule() *ModuleProto {
	if x != nil {
		return x.NewModule
	}
	return nil
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type OutputLine struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Stream            OutputLine_Stream      `protobuf:"varint,1,opt,name=stream,proto3,enum=glix.v1.OutputLine_Stream" json:"stream,omitempty"`
	Line              string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OutputLine) Reset() {
	*x = OutputLine{}
	mi := &file_proto_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputLine) ProtoMessage() {}

func (x *OutputLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputLine.ProtoReflect.Descriptor instead.
func (*OutputLine) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *OutputLine) GetStream() OutputLine_Stream {
	if x != nil {
		return x.Stream
	}
	return OutputLine_STDOUT
}

func (x *OutputLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *OutputLine) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

type ProgressUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Phase           string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"` // e.g., "downloading", "compiling", "installing"
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PercentComplete int32                  `protobuf:"varint,3,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"` // 0-100, -1 if unknown
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_proto_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *ProgressUpdate) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

type InstallProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*InstallProgress_Output
	//	*InstallProgress_Progress
	//	*InstallProgress_Result
	Update        isInstallProgress_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallProgress) Reset() {
	*x = InstallProgress{}
	mi := &file_proto_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallProgress) ProtoMessage() {}

func (x *InstallProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallProgress.ProtoReflect.Descriptor instead.
func (*InstallProgress) Descriptor() ([]byte, []int) {
	return file_proto_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *InstallProgress) GetUpdate() isInstallProgress_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *InstallProgress) GetOutput() *OutputLine {
	if x != nil {
		if x, ok := x.Update.(*InstallProgress_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *InstallProgress) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Update.(*InstallProgress_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *InstallProgress) GetResult() *InstallResponse {
	if x != nil {
		if x, ok := x.Update.(*InstallProgress_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isInstallProgress_Update interface {
	isInstallProgress_Update()
}

type InstallProgress_Output struct {
	Output *OutputLine `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type InstallProgress_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type InstallProgress_Result struct {
	Result *InstallResponse `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*InstallProgress_Output) isInstallProgress_Update() {}

func (*InstallProgress_Progress) isInstallProgress_Update() {}

func (*InstallProgress_Result) isInstallProgress_Update() {}

var File_proto_v1_service_proto protoreflect.FileDescriptor

const file_proto_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/service.proto\x12\aglix.v1\x1a\x17proto/v1/database.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\fServerConfig\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rdatabase_path\x18\x02 \x01(\tR\fdatabasePath\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12!\n" +
	"\fbind_address\x18\x04 \x01(\tR\vbindAddress\"\xcf\x01\n" +
	"\fServerStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12#\n" +
	"\rdatabase_path\x18\x03 \x01(\tR\fdatabasePath\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fmodule_count\x18\x06 \x01(\x03R\vmoduleCount\"\x84\x01\n" +
	"\x12StoreModuleRequest\x12-\n" +
	"\x06module\x18\x01 \x01(\v2\x15.database.ModuleProtoR\x06module\x12?\n" +
	"\fdependencies\x18\x02 \x01(\v2\x1b.database.DependenciesProtoR\fdependencies\"T\n" +
	"\x13StoreModuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x86\x01\n" +
	"\x0eInstallRequest\x12\x1f\n" +
	"\vmodule_path\x18\x01 \x01(\tR\n" +
	"modulePath\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12#\n" +
	"\rstream_output\x18\x04 \x01(\bR\fstreamOutput\"\x7f\n" +
	"\x0fInstallResponse\x12-\n" +
	"\x06module\x18\x01 \x01(\v2\x15.database.ModuleProtoR\x06module\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"J\n" +
	"\rRemoveRequest\x12\x1f\n" +
	"\vmodule_path\x18\x01 \x01(\tR\n" +
	"modulePath\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"O\n" +
	"\x0eRemoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"c\n" +
	"\x12ListModulesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vname_filter\x18\x03 \x01(\tR\n" +
	"nameFilter\"g\n" +
	"\x13ListModulesResponse\x12/\n" +
	"\amodules\x18\x01 \x03(\v2\x15.database.ModuleProtoR\amodules\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"@\n" +
	"\x10GetModuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"X\n" +
	"\x11GetModuleResponse\x12-\n" +
	"\x06module\x18\x01 \x01(\v2\x15.database.ModuleProtoR\x06module\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"p\n" +
	"\x17GetDependenciesResponse\x12?\n" +
	"\fdependencies\x18\x01 \x01(\v2\x1b.database.DependenciesProtoR\fdependencies\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"U\n" +
	"\rUpdateRequest\x12\x1f\n" +
	"\vmodule_path\x18\x01 \x01(\tR\n" +
	"modulePath\x12#\n" +
	"\rstream_output\x18\x02 \x01(\bR\fstreamOutput\"\xbb\x01\n" +
	"\x0eUpdateResponse\x124\n" +
	"\n" +
	"old_module\x18\x01 \x01(\v2\x15.database.ModuleProtoR\toldModule\x124\n" +
	"\n" +
	"new_module\x18\x02 \x01(\v2\x15.database.ModuleProtoR\tnewModule\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xa6\x01\n" +
	"\n" +
	"OutputLine\x122\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1a.glix.v1.OutputLine.StreamR\x06stream\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"k\n" +
	"\x0eProgressUpdate\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10percent_complete\x18\x03 \x01(\x05R\x0fpercentComplete\"\xb5\x01\n" +
	"\x0fInstallProgress\x12-\n" +
	"\x06output\x18\x01 \x01(\v2\x13.glix.v1.OutputLineH\x00R\x06output\x125\n" +
	"\bprogress\x18\x02 \x01(\v2\x17.glix.v1.ProgressUpdateH\x00R\bprogress\x122\n" +
	"\x06result\x18\x03 \x01(\v2\x18.glix.v1.InstallResponseH\x00R\x06resultB\b\n" +
	"\x06update2\xe4\x03\n" +
	"\vGlixService\x12H\n" +
	"\vStoreModule\x12\x1b.glix.v1.StoreModuleRequest\x1a\x1c.glix.v1.StoreModuleResponse\x12H\n" +
	"\vListModules\x12\x1b.glix.v1.ListModulesRequest\x1a\x1c.glix.v1.ListModulesResponse\x12B\n" +
	"\tGetModule\x12\x19.glix.v1.GetModuleRequest\x1a\x1a.glix.v1.GetModuleResponse\x12N\n" +
	"\x0fGetDependencies\x12\x19.glix.v1.GetModuleRequest\x1a .glix.v1.GetDependenciesResponse\x129\n" +
	"\x06Remove\x12\x16.glix.v1.RemoveRequest\x1a\x17.glix.v1.RemoveResponse\x12:\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x15.glix.v1.ServerStatus\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB$Z\"github.com/inovacc/glix/pkg/api/v1b\x06proto3"

var (
	file_proto_v1_service_proto_rawDescOnce sync.Once
	file_proto_v1_service_proto_rawDescData []byte
)

func file_proto_v1_service_proto_rawDescGZIP() []byte {
	file_proto_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_service_proto_rawDesc), len(file_proto_v1_service_proto_rawDesc)))
	})
	return file_proto_v1_service_proto_rawDescData
}

var file_proto_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_v1_service_proto_goTypes = []any{
	(OutputLine_Stream)(0),          // 0: glix.v1.OutputLine.Stream
	(*ServerConfig)(nil),            // 1: glix.v1.ServerConfig
	(*ServerStatus)(nil),            // 2: glix.v1.ServerStatus
	(*StoreModuleRequest)(nil),      // 3: glix.v1.StoreModuleRequest
	(*StoreModuleResponse)(nil),     // 4: glix.v1.StoreModuleResponse
	(*InstallRequest)(nil),          // 5: glix.v1.InstallRequest
	(*InstallResponse)(nil),         // 6: glix.v1.InstallResponse
	(*RemoveRequest)(nil),           // 7: glix.v1.RemoveRequest
	(*RemoveResponse)(nil),          // 8: glix.v1.RemoveResponse
	(*ListModulesRequest)(nil),      // 9: glix.v1.ListModulesRequest
	(*ListModulesResponse)(nil),     // 10: glix.v1.ListModulesResponse
	(*GetModuleRequest)(nil),        // 11: glix.v1.GetModuleRequest
	(*GetModuleResponse)(nil),       // 12: glix.v1.GetModuleResponse
	(*GetDependenciesResponse)(nil), // 13: glix.v1.GetDependenciesResponse
	(*UpdateRequest)(nil),           // 14: glix.v1.UpdateRequest
	(*UpdateResponse)(nil),          // 15: glix.v1.UpdateResponse
	(*OutputLine)(nil),              // 16: glix.v1.OutputLine
	(*ProgressUpdate)(nil),          // 17: glix.v1.ProgressUpdate
	(*InstallProgress)(nil),         // 18: glix.v1.InstallProgress
	(*ModuleProto)(nil),             // 19: database.ModuleProto
	(*DependenciesProto)(nil),       // 20: database.DependenciesProto
	(*emptypb.Empty)(nil),           // 21: google.protobuf.Empty
}
var file_proto_v1_service_proto_depIdxs = []int32{
	19, // 0: glix.v1.StoreModuleRequest.module:type_name -> database.ModuleProto
	20, // 1: glix.v1.StoreModuleRequest.dependencies:type_name -> database.DependenciesProto
	19, // 2: glix.v1.InstallResponse.module:type_name -> database.ModuleProto
	19, // 3: glix.v1.ListModulesResponse.modules:type_name -> database.ModuleProto
	19, // 4: glix.v1.GetModuleResponse.module:type_name -> database.ModuleProto
	20, // 5: glix.v1.GetDependenciesResponse.dependencies:type_name -> database.DependenciesProto
	19, // 6: glix.v1.UpdateResponse.old_module:type_name -> database.ModuleProto
	19, // 7: glix.v1.UpdateResponse.new_module:type_name -> database.ModuleProto
	0,  // 8: glix.v1.OutputLine.stream:type_name -> glix.v1.OutputLine.Stream
	16, // 9: glix.v1.InstallProgress.output:type_name -> glix.v1.OutputLine
	17, // 10: glix.v1.InstallProgress.progress:type_name -> glix.v1.ProgressUpdate
	6,  // 11: glix.v1.InstallProgress.result:type_name -> glix.v1.InstallResponse
	3,  // 12: glix.v1.GlixService.StoreModule:input_type -> glix.v1.StoreModuleRequest
	9,  // 13: glix.v1.GlixService.ListModules:input_type -> glix.v1.ListModulesRequest
	11, // 14: glix.v1.GlixService.GetModule:input_type -> glix.v1.GetModuleRequest
	11, // 15: glix.v1.GlixService.GetDependencies:input_type -> glix.v1.GetModuleRequest
	7,  // 16: glix.v1.GlixService.Remove:input_type -> glix.v1.RemoveRequest
	21, // 17: glix.v1.GlixService.GetStatus:input_type -> google.protobuf.Empty
	21, // 18: glix.v1.GlixService.Ping:input_type -> google.protobuf.Empty
	4,  // 19: glix.v1.GlixService.StoreModule:output_type -> glix.v1.StoreModuleResponse
	10, // 20: glix.v1.GlixService.ListModules:output_type -> glix.v1.ListModulesResponse
	12, // 21: glix.v1.GlixService.GetModule:output_type -> glix.v1.GetModuleResponse
	13, // 22: glix.v1.GlixService.GetDependencies:output_type -> glix.v1.GetDependenciesResponse
	8,  // 23: glix.v1.GlixService.Remove:output_type -> glix.v1.RemoveResponse
	2,  // 24: glix.v1.GlixService.GetStatus:output_type -> glix.v1.ServerStatus
	21, // 25: glix.v1.GlixService.Ping:output_type -> google.protobuf.Empty
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_v1_service_proto_init() }
func file_proto_v1_service_proto_init() {
	if File_proto_v1_service_proto != nil {
		return
	}
	file_proto_v1_database_proto_init()
	file_proto_v1_service_proto_msgTypes[17].OneofWrappers = []any{
		(*InstallProgress_Output)(nil),
		(*InstallProgress_Progress)(nil),
		(*InstallProgress_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_service_proto_rawDesc), len(file_proto_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_v1_service_proto_depIdxs,
		EnumInfos:         file_proto_v1_service_proto_enumTypes,
		MessageInfos:      file_proto_v1_service_proto_msgTypes,
	}.Build()
	File_proto_v1_service_proto = out.File
	file_proto_v1_service_proto_goTypes = nil
	file_proto_v1_service_proto_depIdxs = nil
}
