// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GlixService_StoreModule_FullMethodName     = "/glix.v1.GlixService/StoreModule"
	GlixService_ListModules_FullMethodName     = "/glix.v1.GlixService/ListModules"
	GlixService_GetModule_FullMethodName       = "/glix.v1.GlixService/GetModule"
	GlixService_GetDependencies_FullMethodName = "/glix.v1.GlixService/GetDependencies"
	GlixService_Remove_FullMethodName          = "/glix.v1.GlixService/Remove"
	GlixService_GetStatus_FullMethodName       = "/glix.v1.GlixService/GetStatus"
	GlixService_Ping_FullMethodName            = "/glix.v1.GlixService/Ping"
)

// GlixServiceClient is the client API for GlixService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GlixServiceClient interface {
	// Storage operations (called by CLI after local installation)
	StoreModule(ctx context.Context, in *StoreModuleRequest, opts ...grpc.CallOption) (*StoreModuleResponse, error)
	// Query operations
	ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
	GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetModuleResponse, error)
	GetDependencies(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error)
	// Module management (database only)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	// Server management
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerStatus, error)
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type glixServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGlixServiceClient(cc grpc.ClientConnInterface) GlixServiceClient {
	return &glixServiceClient{cc}
}

func (c *glixServiceClient) StoreModule(ctx context.Context, in *StoreModuleRequest, opts ...grpc.CallOption) (*StoreModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreModuleResponse)
	err := c.cc.Invoke(ctx, GlixService_StoreModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glixServiceClient) ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, GlixService_ListModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glixServiceClient) GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModuleResponse)
	err := c.cc.Invoke(ctx, GlixService_GetModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glixServiceClient) GetDependencies(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDependenciesResponse)
	err := c.cc.Invoke(ctx, GlixService_GetDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glixServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, GlixService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glixServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, GlixService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glixServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GlixService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlixServiceServer is the server API for GlixService service.
// All implementations must embed UnimplementedGlixServiceServer
// for forward compatibility.
type GlixServiceServer interface {
	// Storage operations (called by CLI after local installation)
	StoreModule(context.Context, *StoreModuleRequest) (*StoreModuleResponse, error)
	// Query operations
	ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error)
	GetModule(context.Context, *GetModuleRequest) (*GetModuleResponse, error)
	GetDependencies(context.Context, *GetModuleRequest) (*GetDependenciesResponse, error)
	// Module management (database only)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	// Server management
	GetStatus(context.Context, *emptypb.Empty) (*ServerStatus, error)
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedGlixServiceServer()
}

// UnimplementedGlixServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGlixServiceServer struct{}

func (UnimplementedGlixServiceServer) StoreModule(context.Context, *StoreModuleRequest) (*StoreModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreModule not implemented")
}
func (UnimplementedGlixServiceServer) ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModules not implemented")
}
func (UnimplementedGlixServiceServer) GetModule(context.Context, *GetModuleRequest) (*GetModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModule not implemented")
}
func (UnimplementedGlixServiceServer) GetDependencies(context.Context, *GetModuleRequest) (*GetDependenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDependencies not implemented")
}
func (UnimplementedGlixServiceServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedGlixServiceServer) GetStatus(context.Context, *emptypb.Empty) (*ServerStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedGlixServiceServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGlixServiceServer) mustEmbedUnimplementedGlixServiceServer() {}
func (UnimplementedGlixServiceServer) testEmbeddedByValue()                     {}

// UnsafeGlixServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlixServiceServer will
// result in compilation errors.
type UnsafeGlixServiceServer interface {
	mustEmbedUnimplementedGlixServiceServer()
}

func RegisterGlixServiceServer(s grpc.ServiceRegistrar, srv GlixServiceServer) {
	// If the following call panics, it indicates UnimplementedGlixServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GlixService_ServiceDesc, srv)
}

func _GlixService_StoreModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlixServiceServer).StoreModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlixService_StoreModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlixServiceServer).StoreModule(ctx, req.(*StoreModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlixService_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlixServiceServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlixService_ListModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlixServiceServer).ListModules(ctx, req.(*ListModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlixService_GetModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlixServiceServer).GetModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlixService_GetModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlixServiceServer).GetModule(ctx, req.(*GetModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlixService_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlixServiceServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlixService_GetDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlixServiceServer).GetDependencies(ctx, req.(*GetModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlixService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlixServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlixService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlixServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlixService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlixServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlixService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlixServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlixService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlixServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlixService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlixServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GlixService_ServiceDesc is the grpc.ServiceDesc for GlixService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlixService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "glix.v1.GlixService",
	HandlerType: (*GlixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreModule",
			Handler:    _GlixService_StoreModule_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _GlixService_ListModules_Handler,
		},
		{
			MethodName: "GetModule",
			Handler:    _GlixService_GetModule_Handler,
		},
		{
			MethodName: "GetDependencies",
			Handler:    _GlixService_GetDependencies_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _GlixService_Remove_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _GlixService_GetStatus_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _GlixService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/service.proto",
}
