// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package sqlc

import (
	"context"
)

const CountDependencies = `-- name: CountDependencies :one
SELECT COUNT(*) FROM dependencies
`

func (q *Queries) CountDependencies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDependencies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetDependenciesByModule = `-- name: GetDependenciesByModule :many
SELECT module_name, dep_name, dep_version, dep_hash FROM dependencies
WHERE module_name = ?
`

func (q *Queries) GetDependenciesByModule(ctx context.Context, moduleName string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, GetDependenciesByModule, moduleName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.ModuleName,
			&i.DepName,
			&i.DepVersion,
			&i.DepHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertDependency = `-- name: UpsertDependency :exec
INSERT INTO dependencies (module_name, dep_name, dep_version, dep_hash)
VALUES (?, ?, ?, ?)
ON CONFLICT(module_name, dep_name) DO UPDATE
SET dep_version = excluded.dep_version,
    dep_hash = excluded.dep_hash
`

type UpsertDependencyParams struct {
	ModuleName string  `json:"module_name"`
	DepName    string  `json:"dep_name"`
	DepVersion *string `json:"dep_version"`
	DepHash    *string `json:"dep_hash"`
}

func (q *Queries) UpsertDependency(ctx context.Context, arg UpsertDependencyParams) error {
	_, err := q.db.ExecContext(ctx, UpsertDependency,
		arg.ModuleName,
		arg.DepName,
		arg.DepVersion,
		arg.DepHash,
	)
	return err
}
