// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Dependency struct {
	ModuleName string  `json:"module_name"`
	DepName    string  `json:"dep_name"`
	DepVersion *string `json:"dep_version"`
	DepHash    *string `json:"dep_hash"`
}

type Module struct {
	Name         string     `json:"name"`
	Version      string     `json:"version"`
	Versions     string     `json:"versions"`
	Dependencies string     `json:"dependencies"`
	Hash         *string    `json:"hash"`
	Time         *time.Time `json:"time"`
}
