// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package sqlc

import (
	"context"
	"time"
)

const CountModules = `-- name: CountModules :one
SELECT COUNT(*) FROM modules
`

func (q *Queries) CountModules(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountModules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteModule = `-- name: DeleteModule :exec
DELETE FROM modules
WHERE name = ? AND version = ?
`

type DeleteModuleParams struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) DeleteModule(ctx context.Context, arg DeleteModuleParams) error {
	_, err := q.db.ExecContext(ctx, DeleteModule, arg.Name, arg.Version)
	return err
}

const GetModule = `-- name: GetModule :one
SELECT name, version, versions, dependencies, hash, time FROM modules
WHERE name = ? AND version = ?
LIMIT 1
`

type GetModuleParams struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) GetModule(ctx context.Context, arg GetModuleParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, GetModule, arg.Name, arg.Version)
	var i Module
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.Versions,
		&i.Dependencies,
		&i.Hash,
		&i.Time,
	)
	return i, err
}

const GetModuleByName = `-- name: GetModuleByName :many
SELECT name, version, versions, dependencies, hash, time FROM modules
WHERE name = ?
ORDER BY time DESC
`

func (q *Queries) GetModuleByName(ctx context.Context, name string) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, GetModuleByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Versions,
			&i.Dependencies,
			&i.Hash,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListModules = `-- name: ListModules :many
SELECT name, version, versions, dependencies, hash, time FROM modules
ORDER BY time DESC
`

func (q *Queries) ListModules(ctx context.Context) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, ListModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Versions,
			&i.Dependencies,
			&i.Hash,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertModule = `-- name: UpsertModule :exec
INSERT INTO modules (name, version, versions, dependencies, hash, time)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(name, version) DO UPDATE
SET hash = excluded.hash,
    time = excluded.time,
    versions = excluded.versions,
    dependencies = excluded.dependencies
`

type UpsertModuleParams struct {
	Name         string     `json:"name"`
	Version      string     `json:"version"`
	Versions     string     `json:"versions"`
	Dependencies string     `json:"dependencies"`
	Hash         *string    `json:"hash"`
	Time         *time.Time `json:"time"`
}

func (q *Queries) UpsertModule(ctx context.Context, arg UpsertModuleParams) error {
	_, err := q.db.ExecContext(ctx, UpsertModule,
		arg.Name,
		arg.Version,
		arg.Versions,
		arg.Dependencies,
		arg.Hash,
		arg.Time,
	)
	return err
}
