// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountDependencies(ctx context.Context) (int64, error)
	CountModules(ctx context.Context) (int64, error)
	DeleteModule(ctx context.Context, arg DeleteModuleParams) error
	GetDependenciesByModule(ctx context.Context, moduleName string) ([]Dependency, error)
	GetModule(ctx context.Context, arg GetModuleParams) (Module, error)
	GetModuleByName(ctx context.Context, name string) ([]Module, error)
	ListModules(ctx context.Context) ([]Module, error)
	UpsertDependency(ctx context.Context, arg UpsertDependencyParams) error
	UpsertModule(ctx context.Context, arg UpsertModuleParams) error
}

var _ Querier = (*Queries)(nil)
